# Generated by Django 5.1.1 on 2025-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('Venue', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('date_time1', models.DateTimeField(null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinator_name', models.CharField(blank=True, max_length=50, null=True)),
                ('person', models.CharField(max_length=20)),
            ],
        ),
    ]
